#!/usr/bin/env julia
"""
setup_pressure_sweep.jl

Create folder structure for GCMC/MD simulations at multiple pressures.
Each pressure gets its own directory with initial files copied in.

Usage:
  julia setup_pressure_sweep.jl --pressures 1e3,1e4,1e5,5e5,1e6 \\
      --initial-data loaded_zeolite.lmp \\
      --initial-cif relaxed_MFI.cif \\
      --temperature 300 \\
      --base-dir ./MFI_ethanol_sweep

Creates:
  MFI_ethanol_sweep/
  ├── P_1.0e3/
  │   ├── iter_001/
  │   ├── initial.lmp       (copy of data file)
  │   ├── framework.cif     (copy of CIF)
  │   ├── config.toml       (pressure, temperature, paths)
  │   └── convergence.csv   (tracking file, created during run)
  ├── P_1.0e4/
  └── ...
"""

#using Printf

function main(args=ARGS)
    pressures = Float64[]
    initial_data = ""
    initial_cif = ""
    temperature = 300.0
    base_dir = "./pressure_sweep"
    max_iter = 50

    i = 1
    while i <= length(args)
        a = args[i]
        if a == "--pressures" && i < length(args)
            pressures = parse.(Float64, split(args[i+1], ",")); i += 2
        elseif a == "--initial-data" && i < length(args)
            initial_data = args[i+1]; i += 2
        elseif a == "--initial-cif" && i < length(args)
            initial_cif = args[i+1]; i += 2
        elseif a == "--temperature" && i < length(args)
            temperature = parse(Float64, args[i+1]); i += 2
        elseif a == "--base-dir" && i < length(args)
            base_dir = args[i+1]; i += 2
        elseif a == "--max-iter" && i < length(args)
            max_iter = parse(Int, args[i+1]); i += 2
        else
            i += 1
        end
    end

    if isempty(pressures) || isempty(initial_data) || isempty(initial_cif)
        println("""
        Usage: julia setup_pressure_sweep.jl \\
            --pressures 1e3,1e4,1e5,5e5,1e6 \\
            --initial-data loaded_zeolite.lmp \\
            --initial-cif relaxed_MFI.cif \\
            [--temperature 300] [--base-dir ./sweep] [--max-iter 50]
        """)
        return
    end

    mkpath(base_dir)
    println("Setting up pressure sweep in $base_dir")
    println("  Pressures: $(join([@sprintf("%.1e", p) for p in pressures], ", ")) Pa")
    println("  Temperature: $temperature K")

    for p in pressures
        pname = @sprintf("P_%.1e", p)
        pdir = joinpath(base_dir, pname)
        mkpath(joinpath(pdir, "iter_001", "raspa"))
        mkpath(joinpath(pdir, "iter_001", "lammps"))

        # Copy initial files
        cp(initial_data, joinpath(pdir, "initial.lmp"); force=true)
        cp(initial_cif, joinpath(pdir, "framework.cif"); force=true)

        # Write config for this pressure point
        open(joinpath(pdir, "config.toml"), "w") do io
            println(io, "# Auto-generated by setup_pressure_sweep.jl")
            println(io, "pressure = $p")
            println(io, "temperature = $temperature")
            println(io, "max_iterations = $max_iter")
            println(io, "initial_data = \"initial.lmp\"")
            println(io, "initial_cif = \"framework.cif\"")
        end

        println("  Created $pname/")
    end

    # Write a master run script
    open(joinpath(base_dir, "run_all.sh"), "w") do io
        println(io, "#!/bin/bash")
        println(io, "# Run all pressure points (sequential)")
        println(io, "# Modify to use sbatch/srun for HPC")
        for p in pressures
            pname = @sprintf("P_%.1e", p)
            println(io, "echo \"=== $pname ===\"")
            println(io, "cd $pname && julia ../scripts/run_workflow.jl --config config.toml && cd ..")
        end
    end
    chmod(joinpath(base_dir, "run_all.sh"), 0o755)

    println("\nDone! Run with: cd $base_dir && bash run_all.sh")
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
